[package]
name = "mpc-wallet-core-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.143"
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.76", features = ["console"] }
getrandom = { version = "0.2.15", features = ["js"] }
hex = "0.4.3"
base64 = "0.21"

# Use our shared frost-core library
mpc-wallet-frost-core = { path = "../frost-core" }

# Still need these for specific types
frost-secp256k1 = { version = "2.2.0", features = ["serde"] }
frost-ed25519 = { version = "2.2.0", features = ["serde"] }

# For random number generation
rand = "0.8.5"

[features]
default = ["console_error_panic_hook"]

[dev-dependencies]
wasm-bindgen-test = "0.3.49"
