# Docker Compose configuration for MPC Wallet TUI development/testing
version: '3.8'

services:
  # Signal server for WebRTC coordination
  signal-server:
    build:
      context: ../signal-server/server
      dockerfile: Dockerfile
    container_name: mpc-signal-server
    ports:
      - "9000:9000"
    environment:
      - RUST_LOG=info
      - BIND_ADDRESS=0.0.0.0:9000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - mpc-network

  # MPC Node 1
  mpc-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpc-node-1
    depends_on:
      signal-server:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - DEVICE_ID=mpc-1
      - SIGNAL_SERVER=ws://signal-server:9000
    command: ["--signal-server", "ws://signal-server:9000", "--device-id", "mpc-1"]
    volumes:
      - mpc1_data:/opt/mpc-wallet/data
    restart: unless-stopped
    networks:
      - mpc-network

  # MPC Node 2
  mpc-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpc-node-2
    depends_on:
      signal-server:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - DEVICE_ID=mpc-2
      - SIGNAL_SERVER=ws://signal-server:9000
    command: ["--signal-server", "ws://signal-server:9000", "--device-id", "mpc-2"]
    volumes:
      - mpc2_data:/opt/mpc-wallet/data
    restart: unless-stopped
    networks:
      - mpc-network

  # MPC Node 3
  mpc-node-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpc-node-3
    depends_on:
      signal-server:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - DEVICE_ID=mpc-3
      - SIGNAL_SERVER=ws://signal-server:9000
    command: ["--signal-server", "ws://signal-server:9000", "--device-id", "mpc-3"]
    volumes:
      - mpc3_data:/opt/mpc-wallet/data
    restart: unless-stopped
    networks:
      - mpc-network

volumes:
  mpc1_data:
    driver: local
  mpc2_data:
    driver: local  
  mpc3_data:
    driver: local

networks:
  mpc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16