[package]
name = "mpc-wallet-blockchain"
version = "0.1.0"
edition = "2024"
authors = ["MPC Wallet Team"]
description = "Blockchain support for MPC Wallet"
license = "MIT"

[dependencies]
# Bitcoin dependencies
bitcoin = "0.32.7"

# Ethereum dependencies  
web3 = "0.19.0"
ethers-core = { version = "2.0.14", default-features = false }
hex = "0.4.3"

# Solana dependencies
solana-sdk = "3.0.0"
solana-client = "3.0.1"
spl-token = "6.0.0"
bs58 = "0.5.1"

# Common dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.42.0", features = ["full"] }
async-trait = "0.1.83"
thiserror = "2.0.9"
anyhow = "1.0.99"
tracing = "0.1.41"
sha2 = "0.10.8"
sha3 = "0.10.8"

[lib]
name = "mpc_wallet_blockchain"
path = "src/mod.rs"