[package]
name = "mpc-wallet-blockchain"
version = "0.1.0"
edition = "2024"
authors = ["MPC Wallet Team"]
description = "Blockchain support for MPC Wallet"
license = "MIT"

[dependencies]
# Bitcoin dependencies
bitcoin = "0.32"

# Ethereum dependencies  
web3 = "0.19"
ethers-core = { version = "2.0", default-features = false }
hex = "0.4"

# Solana dependencies
solana-sdk = "3.0.0"
solana-client = "3.0.1"
spl-token = "4.0"
bs58 = "0.5"

# Common dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["full"] }
async-trait = "0.1"
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
sha2 = "0.10"
sha3 = "0.10"

[lib]
name = "mpc_wallet_blockchain"
path = "src/mod.rs"