[test]
# Enable test coverage by default
coverage = true
# Skip test files themselves from being included in coverage
coverageSkipTestFiles = true
# Generate both text and lcov coverage reports
coverageReporter = ["text", "lcov"]

# Path mapping for module resolution
[test]
preload = ["./tests/setup-bun.ts"]

# Module resolution paths
[resolve.alias]
"#imports" = "./tests/__mocks__/imports.ts"
